name: fba-training
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - cobra
  - escher
  - ipywidgets
  - notebook>=6
  - nodejs
  - nb_conda_kernels
  - pip
  - pip:
      - escher
